name: FATFS Build Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WOLFSSL_REF: master

jobs:
  build_wolfssl:
    name: Build wolfssl
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Checking cache for wolfssl
        uses: actions/cache@v4
        id: cache-wolfssl
        with:
          path: build-dir/
          key: wolfssh-fatfs-check-wolfssl-${{ env.WOLFSSL_REF }}
          lookup-only: true

      - name: Checkout, build, and install wolfssl
        if: steps.cache-wolfssl.outputs.cache-hit != 'true'
        uses: wolfSSL/actions-build-autotools-project@v1
        with:
          repository: wolfssl/wolfssl
          ref: ${{ env.WOLFSSL_REF }}
          path: wolfssl
          configure: --enable-wolfssh --enable-cryptonly
          check: false
          install: true

  build_wolfssh:
    name: Build wolfssh with FATFS
    runs-on: ubuntu-latest
    timeout-minutes: 4
    needs: build_wolfssl
    steps:
      - name: Checking cache for wolfssl
        uses: actions/cache@v4
        with:
          path: build-dir/
          key: wolfssh-fatfs-check-wolfssl-${{ env.WOLFSSL_REF }}
          fail-on-cache-miss: true

      - name: Setup FATFS
        run: |
          git clone https://github.com/abbrev/fatfs.git
          cd fatfs/source
          mkdir -p ${{ github.workspace }}/build-dir/include/{wolfssh,fatfs}
          mkdir -p ${{ github.workspace }}/build-dir/lib/fatfs
          cp *.h ${{ github.workspace }}/build-dir/include/fatfs/
          gcc -c -I${{ github.workspace }}/build-dir/include/fatfs -fPIC *.c
          ar rcs ${{ github.workspace }}/build-dir/lib/fatfs/libfatfs.a *.o
          cp ffconf.h ${{ github.workspace }}/build-dir/include/fatfs/ffconf.h
          echo "#define DIR FATFS_DIR" >> ${{ github.workspace }}/build-dir/include/fatfs/ffconf.h
          echo "#define WOLFSSH_FATFS" > ${{ github.workspace }}/build-dir/include/wolfssh/myFilesystem.h
          echo "#undef WOLFSSH_USER_FILESYSTEM" >> ${{ github.workspace }}/build-dir/include/wolfssh/myFilesystem.h
          echo "#include <ffconf.h>" >> ${{ github.workspace }}/build-dir/include/wolfssh/myFilesystem.h
          echo "#include <ff.h>" >> ${{ github.workspace }}/build-dir/include/wolfssh/myFilesystem.h
          echo "#define WFILE FILE" >> ${{ github.workspace }}/build-dir/include/wolfssh/myFilesystem.h
          echo "#define WFD FILE*" >> ${{ github.workspace }}/build-dir/include/wolfssh/myFilesystem.h
          echo "#define WBADFILE NULL" >> ${{ github.workspace }}/build-dir/include/wolfssh/myFilesystem.h
          echo "static FIL* __fatfs_files[32];" >> ${{ github.workspace }}/build-dir/include/wolfssh/myFilesystem.h
          echo "static inline int ff_fopen(FILE** f, const char* filename, BYTE m) { int idx = 0; while(idx < 32 && __fatfs_files[idx]) idx++; if(idx == 32) return -1; __fatfs_files[idx] = malloc(sizeof(FIL)); int ret = f_open(__fatfs_files[idx], filename, m); if(ret == 0) *f = (FILE*)__fatfs_files[idx]; return ret; }" >> ${{ github.workspace }}/build-dir/include/wolfssh/myFilesystem.h

      - name: Checkout, build, and test wolfssh
        uses: wolfSSL/actions-build-autotools-project@v1
        with:
          repository: wolfssl/wolfssh
          path: wolfssh
          configure: --enable-sftp --enable-all CPPFLAGS="-DWOLFSSH_FATFS -I${{ github.workspace }}/build-dir/include -I${{ github.workspace }}/build-dir/include/fatfs -I${{ github.workspace }}/build-dir/include/wolfssh" LDFLAGS="-L${{ github.workspace }}/build-dir/lib -L${{ github.workspace }}/build-dir/lib/fatfs -lfatfs"
          check: false
